Traceback (most recent call last):
  File "/nfs/cms/martialc/DTUpgrade/scripts/daq/translate.py", line 60, in <module>
    if args.language.lower() == 'it': transr = Translator.from_it(args.cfg_path)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/cms/martialc/DTUpgrade/src/muTel/daq/classes/Translator.py", line 288, in from_it
    return cls(Italian(),mapping_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/cms/martialc/DTUpgrade/src/muTel/daq/classes/Translator.py", line 144, in __init__
    self._cfg = load_yaml(mapping_path, config_directory / Path('daq/mapping'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/cms/martialc/DTUpgrade/src/muTel/utils/paths.py", line 74, in load_yaml
    path = get_yaml(path, default_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/cms/martialc/DTUpgrade/src/muTel/utils/paths.py", line 67, in get_yaml
    return get_file(path,default_dir,['.yaml', '.yml'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/cms/martialc/DTUpgrade/src/muTel/utils/paths.py", line 62, in get_file
    raise ValueError(f"Can't find a file with name {path} and extension in {suffix}!")
ValueError: Can't find a file with name /nfs/cms/martialc/DTUpgrade/cfg/daq/mapping/sxa5_240802_full.yml and extension in ['.yaml', '.yml']!
Entering translator loop...
Dumping 0 lines...
Traceback (most recent call last):
  File "/nfs/cms/martialc/DTUpgrade/src/muTel/daq/classes/Translator.py", line 248, in main_loop
    fields = self.translate_word(int(line)) | {'index' : i}
                                 ^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/cms/martialc/DTUpgrade/scripts/daq/translate.py", line 62, in <module>
    transr.translate(args.src_path, args.out_path,
  File "/nfs/cms/martialc/DTUpgrade/src/muTel/daq/classes/Translator.py", line 231, in translate
    self.main_loop(file,max_buffer=max_buffer, debug = debug, verbose=verbose)
  File "/nfs/cms/martialc/DTUpgrade/src/muTel/daq/classes/Translator.py", line 265, in main_loop
    self.dump_buffer()
  File "/nfs/cms/martialc/DTUpgrade/src/muTel/daq/classes/Translator.py", line 289, in dump_buffer
    table = pa.Table.from_pydict(self.buffer)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 1813, in pyarrow.lib._Tabular.from_pydict
  File "pyarrow/table.pxi", line 5348, in pyarrow.lib._from_pydict
  File "pyarrow/table.pxi", line 3991, in pyarrow.lib.Table.from_arrays
  File "pyarrow/table.pxi", line 3271, in pyarrow.lib.Table.validate
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Column 1 named cell expected length 572348 but got length 0
